version: "3.9"

services:
  firebase-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firebase-api
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
    restart: unless-stopped
